# Generated by Django 5.2.3 on 2025-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(default='7CF760BECF', max_length=10, unique=True),
        ),
    ]
