# Generated by Django 5.2.3 on 2025-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_team_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadmember',
            name='action_role',
            field=models.CharField(choices=[('INFANTRY', 'Infantry'), ('ARMOR', 'Armor'), ('HELI', 'Heli'), ('JET', 'Jet')], default='INFANTRY', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(default='4D18CDEA57', max_length=10, unique=True),
        ),
    ]
